### ISSUE TITLE
emacs 30.1 segfault on RHEL 9 in graphical launch with X forwarding

### ISSUE THREAD

**Issue by jwmelto** [alexmurray/emacs-snap#103]
Running on RHEL 9; 30.1 installed.

After running flawlessly, this morning it stared segfault:

```
Fatal error 11: Segmentation fault
Backtrace:
/snap/emacs/2692/usr/bin/emacs-gtk(+0x1b2750)[0x55d9c11e5750]
/snap/emacs/2692/usr/bin/emacs-gtk(+0x57792)[0x55d9c108a792]
/snap/emacs/2692/usr/bin/emacs-gtk(+0x57cae)[0x55d9c108acae]
/snap/emacs/2692/usr/bin/emacs-gtk(+0x57cb5)[0x55d9c108acb5]
/snap/emacs/2692/usr/bin/emacs-gtk(+0x1b089d)[0x55d9c11e389d]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libc.so.6(+0x45330)[0x7f7e4ddcb330]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xd20e65)[0x7f7e3948be65]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libc.so.6(dl_iterate_phdr+0x1b2)[0x7f7e4df0a002]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xd20efd)[0x7f7e3948befd]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xb836ae)[0x7f7e392ee6ae]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xb87dd6)[0x7f7e392f2dd6]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xb893be)[0x7f7e392f43be]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0x7c50ed)[0x7f7e38f300ed]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0x7c5020)[0x7f7e38f30020]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xe7470)[0x7f7e38852470]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xec10c)[0x7f7e3885710c]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xec305)[0x7f7e38857305]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libGLX_indirect.so.0(+0x306e3)[0x7f7e3aeae6e3]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libGLX_indirect.so.0(+0x35878)[0x7f7e3aeb3878]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libGLX_indirect.so.0(+0x368cf)[0x7f7e3aeb48cf]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libGLX_indirect.so.0(+0x33476)[0x7f7e3aeb1476]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libepoxy.so.0(epoxy_glx_version+0x33)[0x7f7e4da59343]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgdk-3.so.0(+0x985d8)[0x7f7e521f55d8]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgdk-3.so.0(+0x9f844)[0x7f7e521fc844]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgdk-3.so.0(+0x8f133)[0x7f7e521ec133]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgdk-3.so.0(gdk_display_manager_open_display+0xe7)[0x7f7e52196397]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_init_check+0x2a)[0x7f7e5246438a]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_init+0xd)[0x7f7e524643bd]
/snap/emacs/2692/usr/bin/emacs-gtk(+0x163217)[0x55d9c1196217]
/snap/emacs/2692/usr/bin/emacs-gtk(+0x1685db)[0x55d9c119b5db]
/snap/emacs/2692/usr/bin/emacs-gtk(+0x274cf1)[0x55d9c12a7cf1]
/snap/emacs/2692/usr/bin/emacs-gtk(+0x2290fe)[0x55d9c125c0fe]
/snap/emacs/2692/usr/bin/emacs-gtk(+0x2296b8)[0x55d9c125c6b8]
/snap/emacs/2692/usr/bin/emacs-gtk(+0x274cf1)[0x55d9c12a7cf1]
/snap/emacs/2692/usr/bin/emacs-gtk(+0x2290fe)[0x55d9c125c0fe]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/emacs/30.1/native-lisp/30.1-b6b3fba3/preloaded/startup-bbc6ea72-bc20aae4.eln(F636f6d6d616e642d6c696e65_command_line_0+0xb9f)[0x7f7e490125ef]
/snap/emacs/2692/usr/bin/emacs-gtk(+0x2290fe)[0x55d9c125c0fe]
/var/lib/snapd/snap/emacs/2692/usr/bin/../lib/emacs/30.1/native-lisp/30.1-b6b3fba3/preloaded/startup-bbc6ea72-bc20aae4.eln(F6e6f726d616c2d746f702d6c6576656c_normal_top_level_0+0xf00)[0x7f7e4900f3f0]
/snap/emacs/2692/usr/bin/emacs-gtk(+0x227d9e)[0x55d9c125ad9e]
/snap/emacs/2692/usr/bin/emacs-gtk(+0x2285d3)[0x55d9c125b5d3]
/snap/emacs/2692/usr/bin/emacs-gtk(+0x224477)[0x55d9c1257477]
...
Segmentation fault (core dumped)
```

Running `-nw` works, but raises other errors

```
 ■  Warning (initialization): An error occurred while loading ‘/home/jmelton/.emacs.d/init.el’:

Native compiler error: (lambda (arg0 &optional) (let ((f #'yes-or-no-p)) (funcall f arg0))), Compiling /home/jmelton/.emacs.d/eln-cache/30.1-b6b3fba3/subr--trampoline-7965732d6f722d6e6f2d70_yes_or_no_p_0.e\
ln...
/usr/bin/ld: cannot find /lib/x86_64-linux-gnu/libc.so.6
collect2: error: ld returned 1 exit status
libgccjit.so: error: error invoking gcc driver
Internal native compiler error: "failed to compile", "/home/jmelton/.emacs.d/eln-cache/30.1-b6b3fba3/subr--trampoline-7965732d6f722d6e6f2d70_yes_or_no_p_0.eln", "error invoking gcc driver"

Error: native-ice ("failed to compile" "/home/jmelton/.emacs.d/eln-cache/30.1-b6b3fba3/subr--trampoline-7965732d6f722d6e6f2d70_yes_or_no_p_0.eln" "error invoking gcc driver")
  comp--compile-ctxt-to-file0("/home/jmelton/.emacs.d/eln-cache/30.1-b6b3fba3/subr--trampoline-7965732d6f722d6e6f2d70_yes_or_no_p_0.eln")
  comp--compile-ctxt-to-file("/home/jmelton/.emacs.d/eln-cache/30.1-b6b3fba3/subr--trampoline-7965732d6f722d6e6f2d70_yes_or_no_p_0.eln")
  comp--final1()
  load-with-code-conversion("/tmp/emacs-int-comp-subr--trampoline-7965732d6f722d6e6f2d70_yes_or_no_p_0-Zop5L8.el" "/tmp/emacs-int-comp-subr--trampoline-7965732d6f722d6e6f2d70_yes_or_no_p_0-Zop5L8.el" nil t\
)
  command-line-1(("-l" "/tmp/emacs-int-comp-subr--trampoline-7965732d6f722d6e6f2d70_yes_or_no_p_0-Zop5L8.el"))
  command-line()
  normal-top-level()
```

The failure to invoke the gcc driver seems pretty important. Not finding libc is pretty bad too. **Something** changed, and I don't know what. I don't routinely do refreshes, but I removed and re-installed (no change). I tried `--channel=latest/edge` and no change

**Comment by alexmurray** [comment]
Thanks for reporting these issues - I think the native-compilation issue it is very likely the same as #96 - can you please try `--channel=latest/beta` which I hope should fix that.

For the graphical segfault, I hope this is the same issue I am currently debugging in #101 which I hope to have a fix for soon.

**Comment by jwmelto** [comment]
still occurs with latest/beta I can paste the stack trace, but a cursory examination suggests it's the same.

**Comment by alexmurray** [comment]
Damn - thanks for confirming - if you could paste the full stack trace that would be good. Out of interest can you also run the following and paste the output:

```
ls -la /lib64/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by jwmelto** [comment]
Beta stack trace:
```
$ emacs
Fatal error 11: Segmentation fault
Backtrace:
/snap/emacs/2704/usr/bin/emacs-gtk(+0x1b2750)[0x555e6d9b1750]
/snap/emacs/2704/usr/bin/emacs-gtk(+0x57792)[0x555e6d856792]
/snap/emacs/2704/usr/bin/emacs-gtk(+0x57cae)[0x555e6d856cae]
/snap/emacs/2704/usr/bin/emacs-gtk(+0x57cb5)[0x555e6d856cb5]
/snap/emacs/2704/usr/bin/emacs-gtk(+0x1b089d)[0x555e6d9af89d]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libc.so.6(+0x45330)[0x7f1b6b953330]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xd20e65)[0x7f1b57013e65]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libc.so.6(dl_iterate_phdr+0x1b2)[0x7f1b6ba92002]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xd20efd)[0x7f1b57013efd]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xb836ae)[0x7f1b56e766ae]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xb87dd6)[0x7f1b56e7add6]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xb893be)[0x7f1b56e7c3be]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0x7c50ed)[0x7f1b56ab80ed]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0x7c5020)[0x7f1b56ab8020]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xe7470)[0x7f1b563da470]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xec10c)[0x7f1b563df10c]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xec305)[0x7f1b563df305]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libGLX_indirect.so.0(+0x306e3)[0x7f1b58a366e3]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libGLX_indirect.so.0(+0x35878)[0x7f1b58a3b878]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libGLX_indirect.so.0(+0x368cf)[0x7f1b58a3c8cf]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libGLX_indirect.so.0(+0x33476)[0x7f1b58a39476]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libepoxy.so.0(epoxy_glx_version+0x33)[0x7f1b6b5e1343]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgdk-3.so.0(+0x985d8)[0x7f1b6fd7d5d8]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgdk-3.so.0(+0x9f844)[0x7f1b6fd84844]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgdk-3.so.0(+0x8f133)[0x7f1b6fd74133]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgdk-3.so.0(gdk_display_manager_open_display+0xe7)[0x7f1b6fd1e397]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_init_check+0x2a)[0x7f1b6ffec38a]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_init+0xd)[0x7f1b6ffec3bd]
/snap/emacs/2704/usr/bin/emacs-gtk(+0x163217)[0x555e6d962217]
/snap/emacs/2704/usr/bin/emacs-gtk(+0x1685db)[0x555e6d9675db]
/snap/emacs/2704/usr/bin/emacs-gtk(+0x274cf1)[0x555e6da73cf1]
/snap/emacs/2704/usr/bin/emacs-gtk(+0x2290fe)[0x555e6da280fe]
/snap/emacs/2704/usr/bin/emacs-gtk(+0x2296b8)[0x555e6da286b8]
/snap/emacs/2704/usr/bin/emacs-gtk(+0x274cf1)[0x555e6da73cf1]
/snap/emacs/2704/usr/bin/emacs-gtk(+0x2290fe)[0x555e6da280fe]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/emacs/30.1/native-lisp/30.1-b6b3fba3/preloaded/startup-bbc6ea72-bc20aae4.eln(F636f6d6d616e642d6c696e65_command_line_0+0xb9f)[0x7f1b66b9a5ef]
/snap/emacs/2704/usr/bin/emacs-gtk(+0x2290fe)[0x555e6da280fe]
/var/lib/snapd/snap/emacs/2704/usr/bin/../lib/emacs/30.1/native-lisp/30.1-b6b3fba3/preloaded/startup-bbc6ea72-bc20aae4.eln(F6e6f726d616c2d746f702d6c6576656c_normal_top_level_0+0xf00)[0x7f1b66b973f0]
/snap/emacs/2704/usr/bin/emacs-gtk(+0x227d9e)[0x555e6da26d9e]
/snap/emacs/2704/usr/bin/emacs-gtk(+0x2285d3)[0x555e6da275d3]
/snap/emacs/2704/usr/bin/emacs-gtk(+0x224477)[0x555e6da23477]
...
Segmentation fault (core dumped)
```

There is no `/lib/x86_64-linux-gnu` on RHEL 9 (that's more of an Ubuntu path), but
```
$ ls -la /lib64/libc.so.6
-rwxr-xr-x. 1 root root 2592552 Apr 29  2024 /lib64/libc.so.6
```

Digging further, I can see
```
$ find /snap/core2?/ -name libc.so.6 -ls 2>/dev/null
     1573      0 lrwxrwxrwx   1 root     root           12 Apr 30  2024 /snap/core20/2434/usr/lib/i386-linux-gnu/libc.so.6 -> libc-2.31.so
     6112      0 lrwxrwxrwx   1 root     root           12 Apr 30  2024 /snap/core20/2434/usr/lib/x86_64-linux-gnu/libc.so.6 -> libc-2.31.so
     1590      0 lrwxrwxrwx   1 root     root           12 Apr 30  2024 /snap/core20/2496/usr/lib/i386-linux-gnu/libc.so.6 -> libc-2.31.so
     6137      0 lrwxrwxrwx   1 root     root           12 Apr 30  2024 /snap/core20/2496/usr/lib/x86_64-linux-gnu/libc.so.6 -> libc-2.31.so
     1756   2259 -rwxr-xr-x   1 root     root      2313128 Aug  8  2024 /snap/core24/739/usr/lib/i386-linux-gnu/libc.so.6
     6952   2076 -rwxr-xr-x   1 root     root      2125328 Aug  8  2024 /snap/core24/739/usr/lib/x86_64-linux-gnu/libc.so.6
```
(limited the search by trial and error)

Looking at #96 
```
snap run --shell emacs
/snap/emacs/2704/usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so: undefined symbol: g_assertion_message_cmpint
Failed to load module: /snap/emacs/2704/usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
/snap/emacs/2704/usr/lib/x86_64-linux-gnu/gio/modules/../../gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /snap/emacs/2704/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/lib64/libc.so.6: version `GLIBC_2.38' not found (required by /snap/emacs/2704/usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so)
Failed to load module: /snap/emacs/2704/usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
```

**Comment by alexmurray** [comment]
Ah ok - so when I said to try the beta channel, I meant that it should fix the native-compilation error hopefully - but I realise the segfault will still be an issue - and I am currently trying to fix that as well - can you confirm that with the beta channel of the snap that the native-compilation errors are not appearing anymore?

**Comment by jwmelto** [comment]
confirmed; the beta channel has no issues run `-nw`

**Comment by jwmelto** [comment]
Can you explain why it spontaneously started failing? Does snap auto-refresh in the background? Is there a way to fall back to what worked yesterday?

**Comment by alexmurray** [comment]
Yes snaps auto refresh - apologies that this broke your setup - I am actively trying to get it fixed. In the meantime you can install the previous version using something like: `sudo snap refresh emacs --revision 2652` which should be the last emacs-29.4  (or perhaps revision 2552 may be better).

**Comment by jwmelto** [comment]
I've spent the day fighting with **snap** because my `/var` partition is too small and all these versions of emacs filled it up. After finally flogging **snap** into submission, I installed `--revision 2652` and it still died:

```
[jmelton@cengpu-02 lib]$ sudo snap install emacs --classic --revision 2652
2025-02-26T17:10:38-07:00 INFO Waiting for automatic snapd restart...
emacs (candidate) 29.4 from Alex Murray (alexmurray✪) installed
Channel latest/stable for emacs is closed; temporarily forwarding to candidate.
[jmelton@cengpu-02 lib]$ emacs
Fatal error 11: Segmentation fault
Backtrace:
/snap/emacs/2652/usr/bin/emacs-gtk(+0x1b5cf0)[0x55c43aa26cf0]
/snap/emacs/2652/usr/bin/emacs-gtk(+0x56955)[0x55c43a8c7955]
/snap/emacs/2652/usr/bin/emacs-gtk(+0x56e7d)[0x55c43a8c7e7d]
/snap/emacs/2652/usr/bin/emacs-gtk(+0x56e84)[0x55c43a8c7e84]
/snap/emacs/2652/usr/bin/emacs-gtk(+0x1b3e5d)[0x55c43aa24e5d]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libc.so.6(+0x45330)[0x7f44f4f2c330]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xd20e65)[0x7f44e0932e65]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libc.so.6(dl_iterate_phdr+0x1b2)[0x7f44f506b002]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xd20efd)[0x7f44e0932efd]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xb836ae)[0x7f44e07956ae]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xb87dd6)[0x7f44e0799dd6]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xb893be)[0x7f44e079b3be]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0x7c50ed)[0x7f44e03d70ed]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0x7c5020)[0x7f44e03d7020]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xe7470)[0x7f44dfcf9470]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xec10c)[0x7f44dfcfe10c]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgallium-24.2.8-1ubuntu1~24.04.1.so(+0xec305)[0x7f44dfcfe305]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libGLX_indirect.so.0(+0x306e3)[0x7f44e23556e3]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libGLX_indirect.so.0(+0x35878)[0x7f44e235a878]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libGLX_indirect.so.0(+0x368cf)[0x7f44e235b8cf]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libGLX_indirect.so.0(+0x33476)[0x7f44e2358476]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libepoxy.so.0(epoxy_glx_version+0x33)[0x7f44f4bba343]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgdk-3.so.0(+0x985d8)[0x7f44f93605d8]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgdk-3.so.0(+0x9f844)[0x7f44f9367844]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgdk-3.so.0(+0x8f133)[0x7f44f9357133]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgdk-3.so.0(gdk_display_manager_open_display+0xe7)[0x7f44f9301397]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_init_check+0x2a)[0x7f44f95cf38a]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_init+0xd)[0x7f44f95cf3bd]
/snap/emacs/2652/usr/bin/emacs-gtk(+0x16660c)[0x55c43a9d760c]
/snap/emacs/2652/usr/bin/emacs-gtk(+0x16b9eb)[0x55c43a9dc9eb]
/snap/emacs/2652/usr/bin/emacs-gtk(+0x278d94)[0x55c43aae9d94]
/snap/emacs/2652/usr/bin/emacs-gtk(+0x22dc9e)[0x55c43aa9ec9e]
/snap/emacs/2652/usr/bin/emacs-gtk(+0x22e138)[0x55c43aa9f138]
/snap/emacs/2652/usr/bin/emacs-gtk(+0x278d94)[0x55c43aae9d94]
/snap/emacs/2652/usr/bin/emacs-gtk(+0x22dc9e)[0x55c43aa9ec9e]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/emacs/29.4/native-lisp/29.4-f009b2dc/preloaded/startup-bbc6ea72-6450744b.eln(F636f6d6d616e642d6c696e65_command_line_0+0xba6)[0x7f44f03898d6]
/snap/emacs/2652/usr/bin/emacs-gtk(+0x22dc9e)[0x55c43aa9ec9e]
/var/lib/snapd/snap/emacs/2652/usr/bin/../lib/emacs/29.4/native-lisp/29.4-f009b2dc/preloaded/startup-bbc6ea72-6450744b.eln(F6e6f726d616c2d746f702d6c6576656c_normal_top_level_0+0xdab)[0x7f44f038653b]
/snap/emacs/2652/usr/bin/emacs-gtk(+0x22c82c)[0x55c43aa9d82c]
/snap/emacs/2652/usr/bin/emacs-gtk(+0x22d08a)[0x55c43aa9e08a]
/snap/emacs/2652/usr/bin/emacs-gtk(+0x228647)[0x55c43aa99647]
...
Segmentation fault (core dumped)
```

`--revision 2552` worked. Thanks for the help.

**Comment by jwmelto** [comment]
... sort of. The compile error is present in `--revision 2552`

**Comment by alexmurray** [comment]
Again apologies for all the issues here - I think I have a fix for the segfault issue but am just doing some more testing on my end before I go ahead with it - thanks for your patience.

**Comment by alexmurray** [comment]
I have just committed a fix and have triggered new builds of the snap which are available in the beta channel  - if you can please test it that would be great, then I can promote it to the stable channel.

**Comment by alexmurray** [comment]
Apologies - there was a typo in the fix - I just added another fix ontop which should actually fix it - this should be available in ~45 minutes in the beta channel for testing.

**Comment by alexmurray** [comment]
@jwmelto this sounds like a complicated setup - can you give me any pointers as to how I can recreate this in a local VM for testing?

Can you also try running something for me:

```
ldd /snap/emacs/2724/usr/bin/emacs-gtk
```

And post the output - I want to see if it is trying to load any libraries from the host system. Also do you by any chance have anything custom set in `LD_LIBRARY_PATH` or in `/etc/ld.so.conf` or `/etc/ld.so.conf.d/*` ?

**Comment by alexmurray** [comment]
Sorry I should have been more specific - when you mentioned "this is an X-forwarded display RHEL 9 to MobaXterm" - this is the bit I meant was a complicated setup - if you are able to guide me through creating this in say a local VM that would be great. Otherwise I am not sure I will be able to debug / fix this. And it could well be that there is a chance in the X protocol or similar between what is in your setup and what the X libraries in emacs are expecting and so there may not be a way to fix this (since the snap is now using libraries from Ubuntu 24.04 which is a lot newer than RHEL 9)

**Comment by jwmelto** [comment]
I'll be able to look into it tomorrow.

The server runs RHEL 9. I access it from a PC running [MobaXterm](https://mobaxterm.mobatek.net). One of the best features of this tool is the built-in X server. I connect to the RHEL server via SSH (with X forwarding). Normally, it works flawlessly. Now it doesn't.

**Comment by jwmelto** [comment]
```
$ snap list
Name    Version   Rev    Tracking       Publisher    Notes
core24  20241217  739    latest/stable  canonical✓   base
emacs   30.1      2724   latest/stable  alexmurray✪  classic
snapd   2.67      23545  latest/stable  canonical✓   snapd
$ ldd /snap/emacs/2724/usr/bin/emacs-gtk
        linux-vdso.so.1 (0x00007ffcae18a000)
        libtiff.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libtiff.so.6 (0x00007ff3095e5000)
        libjpeg.so.8 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007ff309560000)
        libpng16.so.16 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libpng16.so.16 (0x00007ff309526000)
        libgif.so.7 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libgif.so.7 (0x00007ff30951a000)
        libwebpdemux.so.2 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libwebpdemux.so.2 (0x00007ff309511000)
        libwebpdecoder.so.3 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libwebpdecoder.so.3 (0x00007ff3094ce000)
        libgtk-3.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0 (0x00007ff308cd9000)
        libgdk-3.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libgdk-3.so.0 (0x00007ff308bd4000)
        libz.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libz.so.1 (0x00007ff308bb6000)
        libpango-1.0.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007ff308b46000)
        libharfbuzz.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007ff308a35000)
        libcairo.so.2 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libcairo.so.2 (0x00007ff3088ea000)
        libgdk_pixbuf-2.0.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007ff3088b9000)
        libgio-2.0.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007ff3086d5000)
        libgobject-2.0.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007ff30866e000)
        libglib-2.0.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007ff30851a000)
        libSM.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libSM.so.6 (0x00007ff30850e000)
        libICE.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libICE.so.6 (0x00007ff3084ed000)
        libX11.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libX11.so.6 (0x00007ff3083a7000)
        libXrender.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libXrender.so.1 (0x00007ff308399000)
        libasound.so.2 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libasound.so.2 (0x00007ff308283000)
        librsvg-2.so.2 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/librsvg-2.so.2 (0x00007ff307c08000)
        libm.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libm.so.6 (0x00007ff307b1c000)
        libacl.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libacl.so.1 (0x00007ff307b0f000)
        libattr.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libattr.so.1 (0x00007ff307b06000)
        libdbus-1.so.3 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007ff307ab2000)
        libXrandr.so.2 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007ff307aa3000)
        libXinerama.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007ff307a9c000)
        libXfixes.so.3 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007ff307a92000)
        libXext.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libXext.so.6 (0x00007ff307a7a000)
        libxml2.so.2 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libxml2.so.2 (0x00007ff30788e000)
        libgpm.so.2 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libgpm.so.2 (0x00007ff307885000)
        libtinfo.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007ff30784f000)
        libselinux.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libselinux.so.1 (0x00007ff307820000)
        libfreetype.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007ff307752000)
        libfontconfig.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007ff3076fd000)
        libotf.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libotf.so.1 (0x00007ff3076e3000)
        libm17n-flt.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libm17n-flt.so.0 (0x00007ff3076d5000)
        libm17n-core.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libm17n-core.so.0 (0x00007ff3076a5000)
        libgnutls.so.30 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007ff30749e000)
        liblcms2.so.2 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/liblcms2.so.2 (0x00007ff307439000)
        libsystemd.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007ff307352000)
        libgmp.so.10 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libgmp.so.10 (0x00007ff3072c8000)
        libgccjit.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libgccjit.so.0 (0x00007ff304bda000)
        libXi.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libXi.so.6 (0x00007ff304bc5000)
        libtree-sitter.so.0.25 => /snap/emacs/2724/usr/bin/../lib/libtree-sitter.so.0.25 (0x00007ff304b8b000)
        libsqlite3.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007ff304a1b000)
        libXcomposite.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007ff304a12000)
        libc.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libc.so.6 (0x00007ff3047ff000)
        libwebp.so.7 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libwebp.so.7 (0x00007ff304782000)
        libzstd.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libzstd.so.1 (0x00007ff3046c6000)
        liblzma.so.5 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/liblzma.so.5 (0x00007ff304693000)
        libLerc.so.4 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libLerc.so.4 (0x00007ff304609000)
        libjbig.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libjbig.so.0 (0x00007ff3045f6000)
        libdeflate.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libdeflate.so.0 (0x00007ff3045e2000)
        /snap/emacs/current/usr/lib64/ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2 (0x00007ff30a044000)
        libgmodule-2.0.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007ff3045da000)
        libpangocairo-1.0.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007ff3045c7000)
        libpangoft2-1.0.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007ff3045a9000)
        libfribidi.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007ff304587000)
        libcairo-gobject.so.2 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x00007ff30457a000)
        libatk-1.0.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007ff30454d000)
        libepoxy.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libepoxy.so.0 (0x00007ff304412000)
        libatk-bridge-2.0.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x00007ff3043d2000)
        libxkbcommon.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007ff304385000)
        libwayland-client.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007ff304373000)
        libwayland-cursor.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007ff304367000)
        libwayland-egl.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007ff304360000)
        libXcursor.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007ff304352000)
        libXdamage.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007ff30434b000)
        libthai.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libthai.so.0 (0x00007ff30433d000)
        libgraphite2.so.3 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007ff304315000)
        libxcb.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libxcb.so.1 (0x00007ff3042e5000)
        libxcb-render.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007ff3042d2000)
        libxcb-shm.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007ff3042cb000)
        libpixman-1.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007ff304218000)
        libmount.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libmount.so.1 (0x00007ff3041c8000)
        libffi.so.8 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libffi.so.8 (0x00007ff3041ba000)
        libpcre2-8.so.0 => /snap/core24/current/lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007ff304120000)
        libuuid.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libuuid.so.1 (0x00007ff304115000)
        libbsd.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libbsd.so.0 (0x00007ff3040fc000)
        libgcc_s.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff3040cc000)
        libicuuc.so.74 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libicuuc.so.74 (0x00007ff303e99000)
        libbz2.so.1.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007ff303e84000)
        libbrotlidec.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007ff303e74000)
        libexpat.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libexpat.so.1 (0x00007ff303e45000)
        libp11-kit.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007ff303c9f000)
        libidn2.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libidn2.so.0 (0x00007ff303c7c000)
        libunistring.so.5 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libunistring.so.5 (0x00007ff303acb000)
        libtasn1.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007ff303ab4000)
        libnettle.so.8 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libnettle.so.8 (0x00007ff303a59000)
        libhogweed.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libhogweed.so.6 (0x00007ff303a0e000)
        libcap.so.2 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libcap.so.2 (0x00007ff303a00000)
        libgcrypt.so.20 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007ff3038b6000)
        liblz4.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/liblz4.so.1 (0x00007ff303892000)
        libisl.so.23 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libisl.so.23 (0x00007ff30369d000)
        libmpc.so.3 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libmpc.so.3 (0x00007ff303678000)
        libmpfr.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libmpfr.so.6 (0x00007ff3035b8000)
        libsharpyuv.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libsharpyuv.so.0 (0x00007ff3035ae000)
        libstdc++.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff3032e3000)
        libatspi.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libatspi.so.0 (0x00007ff3032a2000)
        libdatrie.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007ff303298000)
        libXau.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libXau.so.6 (0x00007ff303290000)
        libXdmcp.so.6 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007ff303286000)
        libblkid.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libblkid.so.1 (0x00007ff303249000)
        libmd.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libmd.so.0 (0x00007ff303237000)
        libicudata.so.74 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libicudata.so.74 (0x00007ff3014d7000)
        libbrotlicommon.so.1 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007ff3014b2000)
        libgpg-error.so.0 => /snap/emacs/2724/usr/bin/../lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007ff30148c000)
```

```
$ echo $LD_LIBRARY_PATH

$ more /etc/ld.so.conf
include ld.so.conf.d/*.conf
$ ls /etc/ld.so.conf.d/*
/etc/ld.so.conf.d/pipewire-jack-x86_64.conf
$ more /etc/ld.so.conf.d/*
/usr/lib64/pipewire-0.3/jack/
$ ls /usr/lib64/pipewire-0.3/jack/
libjacknet.so.0  libjacknet.so.0.3.1001  libjackserver.so.0  libjackserver.so.0.3.1001  libjack.so.0  libjack.so.0.3.1001

```

**Comment by alexmurray** [comment]
Thanks - there doesn't appear to be anything particular revealing... any chance you could explain how I can set up a test VM to try and reproduce this myself?

**Comment by jwmelto** [comment]
I'm not sure what to tell you. The headless server (running emacs snap) is running RHEL 9.4. It has an NVIDIA GPU, if that matters, but since the rendering is done remotely, I wouldn't expect so.

You should be able to create a VM and SSH into it, but if possible I'd suggest it not be on the same physical box as your "remote" session, just to remove any possibility of optimizing out a relevant portion of the interaction. This doesn't seem very complicated to me.

As noted, I connect using MobaXterm from a Windows PC, which automatically enables X forwarding. I've had no issue with X applications using this path on a variety of servers and OS's.

**Comment by alexmurray** [comment]
@jwmelto there have been a bunch of changes to fix a different segfault when running the snap on x11 lately. Any chance you can test the current stable channel and let me know if this is still an issue? Thanks

**Comment by jwmelto** [comment]
Not this week; we've moved on (away from the snap version) so I'm not sure I'll be able to recreate the situation. I'm ok with closing this if I'm an edge case.

**Comment by alexmurray** [comment]
Ok, I'll close this for now but if you do get a chance to test please let me know as I'd prefer to know for certain (and if it is still an issue, to then reopen this issue so we can have an accurate list of any issues with the snap)
